version: '3.8'

services:
  seo-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - API_KEY=${API_KEY}
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: